In [1]:
import pandas as pd
import numpy as np

In [2]:
df0 = pd.read_csv('weatherAUS.csv')

In [3]:
df0.head(5)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0.2,No

In [4]:
m=(df0[['Temp9am','Temp3pm','WindSpeed9am','WindSpeed3pm','Location']])

In [5]:
df=(m.dropna(how="any",axis=0))

In [6]:
df

        Temp9am  Temp3pm  WindSpeed9am  WindSpeed3pm Location
0          16.9     21.8          20.0          24.0   Albury
1          17.2     24.3           4.0          22.0   Albury
2          21.0     23.2          19.0          26.0   Albury
3          18.1     26.5          11.0           9.0   Albury
4          17.8     29.7           7.0          20.0   Albury
5          20.6     28.9          19.0          24.0   Albury
6          18.1     24.6          20.0          24.0   Albury
7          16.3     25.5           6.0          17.0   Albury
8          18.3     30.2           7.0          28.0   Albury
9          20.1     28.2          15.0          11.0   Albury
10         20.4     28.8          17.0           6.0   Albury
11         15.9     17.0          15.0          13.0   Albury
12         17.4     15.8          28.0          28.0   Albury
13         15.8     19.8          24.0          20.0   Albury
15         17.2     18.1          11.0           9.0   Albury
16         18.0     21.5           6.0          20.0   Albury
17         15.5     21.0          24.0          17.0   Albury
18         15.8     23.2          17.0           6.0   Albury
19         19.1     27.3           9.0           9.0   Albury
20         24.5     31.6          17.0          22.0   Albury
21         23.8     30.8          19.0          20.0   Albury
22         20.9     29.0           6.0          13.0   Albury
23         21.5     31.2           4.0          19.0   Albury
24         23.2     33.0           9.0          13.0   Albury
25         26.6     31.2           0.0          26.0   Albury
26         24.6     32.1          13.0          30.0   Albury
27         21.6     26.1          19.0          30.0   Albury
28         12.5     18.2          11.0          22.0   Albury
29         16.9     22.7          17.0          17.0   Albury
30         19.7     25.7          19.0          31.0   Albury
...         ...      ...           ...           ...      ...
142163     16.1     27.2           0.0          20.0    Uluru
142164     16.6     27.3           6.0          11.0    Uluru
142165     13.8     23.5          11.0          13.0    Uluru
142166     13.9     21.0          19.0          13.0    Uluru
142167     11.8     22.3          13.0          17.0    Uluru
142168     11.1     20.2          20.0          28.0    Uluru
142169      9.7     18.3          22.0          24.0    Uluru
142170      6.8     17.6          17.0          22.0    Uluru
142171      8.6     18.9          19.0          17.0    Uluru
142172      9.5     18.6          13.0          15.0    Uluru
142173     10.3     19.8          17.0          24.0    Uluru
142174      7.9     19.9          13.0          28.0    Uluru
142175      9.5     20.5          13.0          20.0    Uluru
142176      9.1     19.0          13.0          26.0    Uluru
142177      8.7     18.9          19.0          24.0    Uluru
142178      8.2     17.4          15.0          20.0    Uluru
142179      8.0     18.8          17.0          17.0    Uluru
142180      8.5     19.2          13.0          17.0    Uluru
142181     10.3     20.3          17.0          19.0    Uluru
142182      8.9     20.3          11.0           7.0    Uluru
142183      8.8     22.1           9.0           7.0    Uluru
142184     12.3     23.3          11.0          11.0    Uluru
142185     11.2     23.1          15.0          17.0    Uluru
142186     11.6     20.0          19.0          26.0    Uluru
142187     11.0     20.3          15.0          17.0    Uluru
142188      9.4     20.9          15.0          13.0    Uluru
142189     10.1     22.4          13.0          11.0    Uluru
142190     10.9     24.5          13.0           9.0    Uluru
142191     12.5     26.1           9.0           9.0    Uluru
142192     15.1     26.0          13.0           7.0    Uluru

[137987 rows x 5 columns]

In [7]:
df1=(df[df["Location"]=="Richmond"][:1000])

In [8]:
df1

       Temp9am  Temp3pm  WindSpeed9am  WindSpeed3pm  Location
26546     20.0     32.1           9.0          31.0  Richmond
26547     20.0     23.7          13.0          35.0  Richmond
26548     16.8     20.0           7.0           9.0  Richmond
26549     19.6     29.3           4.0          17.0  Richmond
26550     21.2     36.1           7.0          24.0  Richmond
26551     22.5     38.0           6.0          11.0  Richmond
26552     22.2     35.8           9.0          19.0  Richmond
26553     20.2     18.3          11.0          19.0  Richmond
26554     16.9     19.9          17.0          13.0  Richmond
26555     17.2     23.3           6.0          19.0  Richmond
26556     19.4     27.8           2.0          17.0  Richmond
26557     17.8     26.4           4.0          30.0  Richmond
26558     22.7     29.3          11.0          17.0  Richmond
26559     22.3     37.0           4.0          13.0  Richmond
26560     29.7     39.9          11.0          24.0  Richmond
26561     19.8     30.7           6.0          11.0  Richmond
26562     15.9     20.0          11.0          17.0  Richmond
26563     18.0     27.1           4.0          11.0  Richmond
26564     18.9     31.9           6.0          19.0  Richmond
26565     22.7     38.5           4.0          19.0  Richmond
26566     26.5     38.1           9.0          17.0  Richmond
26567     26.0     30.9          13.0          22.0  Richmond
26568     29.6     35.0          17.0          19.0  Richmond
26569     32.6     40.5          20.0          35.0  Richmond
26570     21.5     27.2          15.0          13.0  Richmond
26571     22.5     30.1           9.0          19.0  Richmond
26572     20.3     27.3           9.0           9.0  Richmond
26573     19.3     32.9           7.0          17.0  Richmond
26574     21.5     32.8           6.0          11.0  Richmond
26575     24.3     33.3           6.0          13.0  Richmond
...        ...      ...           ...           ...       ...
27545     14.3     16.5          15.0          11.0  Richmond
27547     14.8     18.4          11.0          15.0  Richmond
27548     19.6     29.3           2.0          26.0  Richmond
27549     23.2     28.3          30.0          15.0  Richmond
27550     23.1     30.9          13.0          19.0  Richmond
27551     22.3     32.0           6.0          19.0  Richmond
27552     25.3     29.7          13.0          17.0  Richmond
27553     16.1     20.4          17.0          15.0  Richmond
27554     15.8     18.6          19.0          20.0  Richmond
27555     17.4     23.6           4.0           6.0  Richmond
27556     19.2     15.8           9.0          20.0  Richmond
27557     15.9     18.3          15.0          22.0  Richmond
27558     15.5     17.2           7.0           9.0  Richmond
27559     17.5     19.8           9.0           9.0  Richmond
27560     16.4     18.2           7.0          11.0  Richmond
27561     17.9     24.3           2.0          13.0  Richmond
27562     18.5     24.2           4.0           7.0  Richmond
27563     21.4     19.2           0.0           0.0  Richmond
27564     16.5     18.6          17.0           9.0  Richmond
27565     17.7     22.6          17.0           4.0  Richmond
27566     18.2     20.4          13.0          24.0  Richmond
27567     17.6     22.2           4.0           4.0  Richmond
27568     18.4     20.0           4.0          15.0  Richmond
27569     18.3     21.3           0.0          13.0  Richmond
27570     16.8     23.6           2.0           7.0  Richmond
27571     18.2     22.7           9.0           7.0  Richmond
27572     20.3     23.5          15.0          15.0  Richmond
27573     19.1     22.8           7.0          17.0  Richmond
27574     18.5     20.2           9.0           0.0  Richmond
27575     19.3     25.9           9.0          17.0  Richmond

[1000 rows x 5 columns]

In [9]:
df2=(df[df["Location"]=="Sydney"][:1000])

In [10]:
df2

       Temp9am  Temp3pm  WindSpeed9am  WindSpeed3pm Location
29497     20.7     20.9          17.0          20.0   Sydney
29498     22.4     24.8           9.0          13.0   Sydney
29499     23.5     23.0          17.0           2.0   Sydney
29500     21.4     20.9          22.0          20.0   Sydney
29501     22.5     25.5          11.0           6.0   Sydney
29502     23.8     26.0           9.0          22.0   Sydney
29503     21.7     22.3          15.0          15.0   Sydney
29504     18.9     21.1           7.0          15.0   Sydney
29505     17.1     16.5          19.0           9.0   Sydney
29506     17.2     23.3          11.0          20.0   Sydney
29507     18.9     23.7           9.0          26.0   Sydney
29508     22.9     24.7           7.0          24.0   Sydney
29509     20.9     21.0          24.0          30.0   Sydney
29510     18.4     23.3          15.0          19.0   Sydney
29511     19.5     23.8          19.0          22.0   Sydney
29512     19.8     23.3          11.0          26.0   Sydney
29513     21.8     23.4          13.0          24.0   Sydney
29514     21.2     23.8          13.0          24.0   Sydney
29515     20.8     23.4           7.0          17.0   Sydney
29516     21.3     25.2          13.0          22.0   Sydney
29517     22.1     24.9           4.0          15.0   Sydney
29518     22.3     24.9          11.0          28.0   Sydney
29519     22.5     24.0          20.0          24.0   Sydney
29520     21.2     26.1          11.0          24.0   Sydney
29521     21.6     23.5          15.0          20.0   Sydney
29522     23.0     25.8           2.0          28.0   Sydney
29523     21.3     24.7           0.0          15.0   Sydney
29524     20.4     19.2          20.0           9.0   Sydney
29525     17.1     19.9          24.0          28.0   Sydney
29526     15.9     21.2          19.0          31.0   Sydney
...        ...      ...           ...           ...      ...
30500     13.3     17.8          31.0          24.0   Sydney
30501     17.6     20.7          13.0          24.0   Sydney
30502     14.8     17.6          15.0          20.0   Sydney
30503     15.2     17.8          17.0          30.0   Sydney
30504     14.1     16.7           7.0          15.0   Sydney
30505     16.6     20.7          13.0          26.0   Sydney
30506     23.3     23.8           7.0          28.0   Sydney
30507     19.7     23.2          22.0          11.0   Sydney
30508     20.9     23.5           6.0          30.0   Sydney
30509     20.1     25.0           7.0          24.0   Sydney
30510     25.8     27.6          11.0          28.0   Sydney
30511     26.1     27.2          13.0          28.0   Sydney
30512     23.9     19.4           9.0           7.0   Sydney
30513     18.8     22.8          13.0          20.0   Sydney
30514     17.5     21.0          17.0          15.0   Sydney
30515     22.3     22.6           7.0          20.0   Sydney
30516     17.4     18.5          26.0          33.0   Sydney
30519     19.3     23.2           4.0          26.0   Sydney
30521     22.8     24.1          17.0          26.0   Sydney
30522     22.5     25.2          17.0          20.0   Sydney
30523     23.9     22.4          13.0          19.0   Sydney
30524     22.3     25.5           6.0          28.0   Sydney
30525     21.7     23.0           9.0          13.0   Sydney
30526     18.0     20.8          30.0          28.0   Sydney
30527     17.3     20.2          11.0          17.0   Sydney
30528     18.9     19.9          30.0          19.0   Sydney
30529     20.1     22.7          17.0          22.0   Sydney
30530     23.7     23.2          17.0          24.0   Sydney
30531     20.9     22.0           6.0          19.0   Sydney
30533     23.6     25.5           7.0          19.0   Sydney

[1000 rows x 5 columns]

In [11]:
df3=(df[df["Location"]=="Portland"][:1000])

In [12]:
df3

       Temp9am  Temp3pm  WindSpeed9am  WindSpeed3pm  Location
72756     13.7     14.5          28.0          28.0  Portland
72757     11.9     14.0          20.0          17.0  Portland
72758     11.6     17.5           9.0          15.0  Portland
72759     14.7     18.1          11.0          17.0  Portland
72760     14.9     18.0          20.0          31.0  Portland
72761     15.4     18.9          17.0          26.0  Portland
72762     14.6     17.9           9.0          28.0  Portland
72763     12.9     15.0          20.0          22.0  Portland
72764     14.1     17.2          17.0          19.0  Portland
72765     15.4     17.7          15.0          19.0  Portland
72766     14.0     17.5           0.0          24.0  Portland
72767     16.2     20.8           9.0          13.0  Portland
72768     21.4     36.3          15.0          30.0  Portland
72769     15.4     17.2          17.0          15.0  Portland
72770     16.7     18.2          20.0          30.0  Portland
72771     14.6     15.7          28.0          26.0  Portland
72772     14.5     17.2           9.0          15.0  Portland
72773     14.1     20.9          13.0          19.0  Portland
72774     16.9     26.0           9.0          20.0  Portland
72775     18.0     24.6           9.0          20.0  Portland
72776     16.3     21.2          17.0          35.0  Portland
72777     21.7     17.8          44.0          41.0  Portland
72778     12.8     21.4          15.0          31.0  Portland
72779     15.3     17.3          28.0          28.0  Portland
72780     13.8     19.6           7.0          24.0  Portland
72781     16.6     20.4           9.0          19.0  Portland
72782     15.5     32.1          15.0          15.0  Portland
72783     27.5     33.4          11.0          15.0  Portland
72784     31.3     36.5          19.0          28.0  Portland
72785     23.2     23.7          13.0          19.0  Portland
...        ...      ...           ...           ...       ...
73780     13.7     17.5          13.0          24.0  Portland
73781     15.2     19.4          15.0          20.0  Portland
73782     15.4     16.4          11.0          24.0  Portland
73783     13.7     16.0          11.0          19.0  Portland
73784     13.7     17.3           9.0           9.0  Portland
73785     19.0     25.3           9.0          20.0  Portland
73786     12.4     14.2          31.0          37.0  Portland
73787     13.9     16.2          17.0          17.0  Portland
73788     13.3     16.0           9.0          13.0  Portland
73789     14.6     15.1          11.0          20.0  Portland
73790     12.6     13.5          20.0          24.0  Portland
73791     14.8     17.3          24.0          26.0  Portland
73792     13.9     20.2          22.0          15.0  Portland
73793     17.5     22.0          11.0          15.0  Portland
73794     19.2     23.1           4.0          11.0  Portland
73795     18.2     19.7           9.0          17.0  Portland
73796     19.8     19.7          17.0          19.0  Portland
73797     15.0     16.2          15.0          19.0  Portland
73798     15.1     17.1          17.0          28.0  Portland
73800     16.0     17.6          20.0          26.0  Portland
73801     16.2     20.6          20.0          24.0  Portland
73802     17.2     27.2          20.0          19.0  Portland
73803     20.4     20.3          26.0          20.0  Portland
73804     15.3     15.7          26.0          26.0  Portland
73805     16.6     19.1           9.0          19.0  Portland
73806     15.1     17.8          17.0          17.0  Portland
73807     16.7     22.5          20.0          17.0  Portland
73808     17.0     22.0          17.0          15.0  Portland
73809     19.0     22.7          11.0          20.0  Portland
73810     17.4     21.2          26.0          24.0  Portland

[1000 rows x 5 columns]

In [13]:
df_new=pd.concat((df1,df2,df3))

In [14]:
df_new

       Temp9am  Temp3pm  WindSpeed9am  WindSpeed3pm  Location
26546     20.0     32.1           9.0          31.0  Richmond
26547     20.0     23.7          13.0          35.0  Richmond
26548     16.8     20.0           7.0           9.0  Richmond
26549     19.6     29.3           4.0          17.0  Richmond
26550     21.2     36.1           7.0          24.0  Richmond
26551     22.5     38.0           6.0          11.0  Richmond
26552     22.2     35.8           9.0          19.0  Richmond
26553     20.2     18.3          11.0          19.0  Richmond
26554     16.9     19.9          17.0          13.0  Richmond
26555     17.2     23.3           6.0          19.0  Richmond
26556     19.4     27.8           2.0          17.0  Richmond
26557     17.8     26.4           4.0          30.0  Richmond
26558     22.7     29.3          11.0          17.0  Richmond
26559     22.3     37.0           4.0          13.0  Richmond
26560     29.7     39.9          11.0          24.0  Richmond
26561     19.8     30.7           6.0          11.0  Richmond
26562     15.9     20.0          11.0          17.0  Richmond
26563     18.0     27.1           4.0          11.0  Richmond
26564     18.9     31.9           6.0          19.0  Richmond
26565     22.7     38.5           4.0          19.0  Richmond
26566     26.5     38.1           9.0          17.0  Richmond
26567     26.0     30.9          13.0          22.0  Richmond
26568     29.6     35.0          17.0          19.0  Richmond
26569     32.6     40.5          20.0          35.0  Richmond
26570     21.5     27.2          15.0          13.0  Richmond
26571     22.5     30.1           9.0          19.0  Richmond
26572     20.3     27.3           9.0           9.0  Richmond
26573     19.3     32.9           7.0          17.0  Richmond
26574     21.5     32.8           6.0          11.0  Richmond
26575     24.3     33.3           6.0          13.0  Richmond
...        ...      ...           ...           ...       ...
73780     13.7     17.5          13.0          24.0  Portland
73781     15.2     19.4          15.0          20.0  Portland
73782     15.4     16.4          11.0          24.0  Portland
73783     13.7     16.0          11.0          19.0  Portland
73784     13.7     17.3           9.0           9.0  Portland
73785     19.0     25.3           9.0          20.0  Portland
73786     12.4     14.2          31.0          37.0  Portland
73787     13.9     16.2          17.0          17.0  Portland
73788     13.3     16.0           9.0          13.0  Portland
73789     14.6     15.1          11.0          20.0  Portland
73790     12.6     13.5          20.0          24.0  Portland
73791     14.8     17.3          24.0          26.0  Portland
73792     13.9     20.2          22.0          15.0  Portland
73793     17.5     22.0          11.0          15.0  Portland
73794     19.2     23.1           4.0          11.0  Portland
73795     18.2     19.7           9.0          17.0  Portland
73796     19.8     19.7          17.0          19.0  Portland
73797     15.0     16.2          15.0          19.0  Portland
73798     15.1     17.1          17.0          28.0  Portland
73800     16.0     17.6          20.0          26.0  Portland
73801     16.2     20.6          20.0          24.0  Portland
73802     17.2     27.2          20.0          19.0  Portland
73803     20.4     20.3          26.0          20.0  Portland
73804     15.3     15.7          26.0          26.0  Portland
73805     16.6     19.1           9.0          19.0  Portland
73806     15.1     17.8          17.0          17.0  Portland
73807     16.7     22.5          20.0          17.0  Portland
73808     17.0     22.0          17.0          15.0  Portland
73809     19.0     22.7          11.0          20.0  Portland
73810     17.4     21.2          26.0          24.0  Portland

[3000 rows x 5 columns]

In [15]:
df_new=(df_new.rename(columns={"Temp9am": "0", "Temp3pm": "1", "WindSpeed9am": "2", "WindSpeed3pm": "3", "Location":"4"}))

In [16]:
df_new

          0     1     2     3         4
26546  20.0  32.1   9.0  31.0  Richmond
26547  20.0  23.7  13.0  35.0  Richmond
26548  16.8  20.0   7.0   9.0  Richmond
26549  19.6  29.3   4.0  17.0  Richmond
26550  21.2  36.1   7.0  24.0  Richmond
26551  22.5  38.0   6.0  11.0  Richmond
26552  22.2  35.8   9.0  19.0  Richmond
26553  20.2  18.3  11.0  19.0  Richmond
26554  16.9  19.9  17.0  13.0  Richmond
26555  17.2  23.3   6.0  19.0  Richmond
26556  19.4  27.8   2.0  17.0  Richmond
26557  17.8  26.4   4.0  30.0  Richmond
26558  22.7  29.3  11.0  17.0  Richmond
26559  22.3  37.0   4.0  13.0  Richmond
26560  29.7  39.9  11.0  24.0  Richmond
26561  19.8  30.7   6.0  11.0  Richmond
26562  15.9  20.0  11.0  17.0  Richmond
26563  18.0  27.1   4.0  11.0  Richmond
26564  18.9  31.9   6.0  19.0  Richmond
26565  22.7  38.5   4.0  19.0  Richmond
26566  26.5  38.1   9.0  17.0  Richmond
26567  26.0  30.9  13.0  22.0  Richmond
26568  29.6  35.0  17.0  19.0  Richmond
26569  32.6  40.5  20.0  35.0  Richmond
26570  21.5  27.2  15.0  13.0  Richmond
26571  22.5  30.1   9.0  19.0  Richmond
26572  20.3  27.3   9.0   9.0  Richmond
26573  19.3  32.9   7.0  17.0  Richmond
26574  21.5  32.8   6.0  11.0  Richmond
26575  24.3  33.3   6.0  13.0  Richmond
...     ...   ...   ...   ...       ...
73780  13.7  17.5  13.0  24.0  Portland
73781  15.2  19.4  15.0  20.0  Portland
73782  15.4  16.4  11.0  24.0  Portland
73783  13.7  16.0  11.0  19.0  Portland
73784  13.7  17.3   9.0   9.0  Portland
73785  19.0  25.3   9.0  20.0  Portland
73786  12.4  14.2  31.0  37.0  Portland
73787  13.9  16.2  17.0  17.0  Portland
73788  13.3  16.0   9.0  13.0  Portland
73789  14.6  15.1  11.0  20.0  Portland
73790  12.6  13.5  20.0  24.0  Portland
73791  14.8  17.3  24.0  26.0  Portland
73792  13.9  20.2  22.0  15.0  Portland
73793  17.5  22.0  11.0  15.0  Portland
73794  19.2  23.1   4.0  11.0  Portland
73795  18.2  19.7   9.0  17.0  Portland
73796  19.8  19.7  17.0  19.0  Portland
73797  15.0  16.2  15.0  19.0  Portland
73798  15.1  17.1  17.0  28.0  Portland
73800  16.0  17.6  20.0  26.0  Portland
73801  16.2  20.6  20.0  24.0  Portland
73802  17.2  27.2  20.0  19.0  Portland
73803  20.4  20.3  26.0  20.0  Portland
73804  15.3  15.7  26.0  26.0  Portland
73805  16.6  19.1   9.0  19.0  Portland
73806  15.1  17.8  17.0  17.0  Portland
73807  16.7  22.5  20.0  17.0  Portland
73808  17.0  22.0  17.0  15.0  Portland
73809  19.0  22.7  11.0  20.0  Portland
73810  17.4  21.2  26.0  24.0  Portland

[3000 rows x 5 columns]

In [17]:
class Perceptron():   # vytvorenie triedy perceptron
    def __init__(self, rychlost_ucenia=0.01, pocet_iteracii=15): # konštruktor - inicializuje atribúty triedy (rýchlosť učenia, počet iterácií)
        self.eta = rychlost_ucenia # priradenie do premennej - prístup k atribútom
        self.n_iter = pocet_iteracii # priradenie do premennej - prístup k atribútom
    
    
    def fit(self, X,y): # metóda procesu učenia 
        self.vahy = np.zeros(1+ X.shape[1]) # šírka poľa váh 
        self.errors_=[] # vytvorenie poľa erorov
        
        self.vahy_to_visualize_1=[] # vytvorenie premenných na vitualizáciu
        self.vahy_to_visualize_2=[]
        self.vahy_to_visualize_3=[]
        
        for i in range(self.n_iter): # cyklus na naplnenie
            errors = 0 # naplnenie matice errors nulami
            for matica,vystup in zip(X,y):
                update = self.eta * (vystup-self.predikcia(matica))
                self.vahy[1:] += update*matica
                self.vahy[0]+= update
                
                print(self.vahy[1:]) # výpis váh
                
                errors += int(update !=0.0)
            self.errors_.append(errors)   
            self.vahy_to_visualize_1.append(self.vahy[0]) # naplnenie premenných
            self.vahy_to_visualize_2.append(self.vahy[1])
            self.vahy_to_visualize_3.append(self.vahy[2])
        return self  

    def net_input(self, X): # výpočet čistého vstupu
        return np.dot(X, self.vahy[1:])+ self.vahy[0]

    def predikcia(self, X): # návrat triedy po kroku
        return np.where(self.net_input(X) >= 0.0, 1, -1)

In [18]:
import matplotlib.pyplot as plt # importovanie knižnice